http:
  routers:
    api-1:
      rule: "PathPrefix(`/api-1`)"
      service: api-1
      middlewares:
      - "middleware-auth-opa"
    api-2:
      rule: "PathPrefix(`/api-2`)"
      service: api-2
      middlewares:
      - "middleware-auth-opa"
    web:
      rule: "PathPrefix(`/`)"
      service: web
  middlewares:
    middleware-auth-opa:
      forwardAuth:
        address: "http://localhost:8180"
  services:
    api-1:
      loadBalancer:
        servers:
        - url: http://localhost:3000/api-1
    api-2:
      loadBalancer:
        servers:
        - url: http://localhost:3000/api-2
    web:
      loadBalancer:
        servers:
        - url: http://localhost:3000